name: 'Build'
description: 'Composite action to build this cmake project'
inputs:
  os:
    required: true
    type: string
    default: 'ubuntu-latest'
  architecture:
    required: true
    type: string
    default: 'x64'
  configuration:
    required: true
    type: string
    default: 'release'
  toolchain:
    required: true
    type: string
outputs:
  build_directory:
    value: './out/build/${{inputs.architecture}}-${{inputs.toolchain}}-${{inputs.configuration}}'

env:
  preset_name: '${{inputs.architecture}}-${{inputs.toolchain}}-${{inputs.configuration}}'
  build_directory: './out/build/${{inputs.architecture}}-${{inputs.toolchain}}-${{inputs.configuration}}'
  CPM_SOURCE_CACHE: '${{github.workspace}}/.cpm_cache'

runs:
  using: "composite"
  steps:
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ env.preset_name }}

    - name: "Cache CPM dependencies"
      uses: actions/cache@v4
      with:
        path: ${{ env.CPM_SOURCE_CACHE }}
        key: cpm-${{ hashFiles('**/*.cmake', '**/CMakeLists.txt') }}
        enableCrossOsArchive: true

    - name: "Install msvc"
      if: ${{matrix.toolchain}} == msvc
      uses: ilammy/msvc-dev-cmd@v1

    - name: "Install CMake and Ninja"
      uses: lukka/get-cmake@latest

    - name: Build
      run: |
        cmake --preset ${{ env.preset_name }}
        cmake --build ${{ env.build_directory }}
