name: "CI Windows"

on:
  push:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/actions/build/action.yml'
      - '.github/workflows/ci_windows.yml'
  pull_request:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/actions/build/action.yml'
      - '.github/workflows/ci_windows.yml'

env:
  CPM_SOURCE_CACHE: '${{github.workspace}}/.cpm_cache'

jobs:
  build:
    name: 'Build and Test ${{matrix.architecture}}-${{matrix.toolchain}}-${{matrix.configuration}}'

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        configuration: [release]
        architecture: [x64]
        toolchain: [clang-cl, msvc]

    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: './.github/actions/build'
        with:
          configuration: ${{ matrix.configuration }}
          architecture: ${{ matrix.architecture }}
          toolchain: ${{ matrix.toolchain }}

      - name: CTest
        working-directory: ${{steps.build.outputs.build_directory}}
        run: ctest
