# Simple workflow for deploying static content to GitHub Pages
name:  Documentation build & deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/documentation.yaml'
      - '**.md'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/.cpm_cache
  preset: x64-clang-release

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Update
        run: |
          sudo apt-add-repository universe
          sudo apt-get update

      - uses: ssciwr/doxygen-install@v1
        with:
          version: "1.12.0"

      - name: Install dependencies
        run: |
          sudo apt-get install graphviz
          pip3 install jinja2 Pygments

      - id: build
        uses: './.github/actions/build'
        with:
          os: $${{ matrix.os }}
          configuration: $${{ matrix.configuration }}
          architecture: $${{ matrix.architecture }}
          toolchain: $${{ matrix.toolchain }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.build.outputs.build_directory }}/doxygen/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
