name: "CI"

on:
  push:
    branches: ["master"]
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/windows.yaml'
  pull_request:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/windows.yaml'

env:
  CPM_SOURCE_PACKAGE:'./.cpm_cache'

jobs:
  build:
    name: 'Build and Test ${{matrix.architecture}}-${{matrix.toolchain}}-${{matrix.configuration}}'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        configuration: [release]
        architecture: [x64]
        toolchain: [clang-cl, msvc]

    steps:
      - uses: actions/checkout@v4
      - id: build
        uses: './.github/actions/build'
        with:
          cpm_source_cache: ${{ env.CPM_SOURCE_CACHE }}
          os: $${{ matrix.os }}
          configuration: $${{ matrix.configuration }}
          architecture: $${{ matrix.architecture }}
          toolchain: $${{ matrix.toolchain }}
      - name: CTest
        working-directory: ${{build.outputs.build_directory}}
        run: ctest
